# Generated by Django 4.2.9 on 2024-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shodki',
            options={'verbose_name': 'Сходка', 'verbose_name_plural': 'Сходки'},
        ),
        migrations.AlterField(
            model_name='shodki',
            name='title',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
    ]
